#!/bin/bash

# Usage:
#   ./ungpgstuff.sh [--symmetric]
# If --symmetric is provided, symmetric decryption will be used with the keyfile at /tmp/keyfile.

SYMMETRIC=true
KEYFILE="/tmp/keyfile"

# Check if the script is called with the --symmetric argument
if [[ "$1" == "--symmetric" ]]; then
    SYMMETRIC=true
fi

for i in *.gpg; do
    
    if [[ "$SYMMETRIC" == true ]]; then
        gpg --batch --yes --passphrase-file "$KEYFILE" -o "$(basename "$i" .gpg).tar" -d $i
    else
        gpg -o "$(basename "$i" .gpg).tar" -d "$i"
    fi
    
    echo extracting....
    rm "$i"
    tar -xf "$(basename "$i" .gpg).tar"
    rm $(basename "$i" .gpg).tar
done
