#!/bin/bash
echo "starting..."

INPUT="$1"
TMPFILE="./transcoded_$(basename "$INPUT")"

# Set this to 1 if you want preview mode (4 chunks + final segment)
        # true lossless
        ffmpeg -y -i "$INPUT" -vf "scale=-2:120,fps=8,format=gray" -an -c:v libx264 -preset ultrafast -qp 0 -tune zerolatency -x264-params cabac=0:bframes=0 -fps_mode cfr "$TMPFILE"

        # absolute garbage
        # ffmpeg -y -i "$INPUT" -vf "scale=-2:120,fps=4,format=gray" -an -crf 51 -c:v libx264 -preset ultrafast -tune zerolatency -x264-params cabac=0:bframes=0 -fps_mode cfr "$TMPFILE"

        mpv --no-correct-pts --framedrop=vo --speed=1 --vo=tct --sws-fast=yes "$TMPFILE"
        rm -f "$TMPFILE"
